package com.example.assis_3;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHANNEL_ITEM.
 */
public class ChannelItem {

    private Long id;
    private String name;
    private Integer orderId;
    private Integer selected;

    public ChannelItem() {
    }

    public ChannelItem(Long id) {
        this.id = id;
    }

    public ChannelItem(Long id, String name, Integer orderId, Integer selected) {
        this.id = id;
        this.name = name;
        this.orderId = orderId;
        this.selected = selected;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getSelected() {
        return selected;
    }

    public void setSelected(Integer selected) {
        this.selected = selected;
    }

}
