package com.example.assis_3;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FEEDBACK_MSG.
 */
public class FeedbackMsg {

    private Long id;
    private String descr;
    private String date;
    private String phoneModel;

    public FeedbackMsg() {
    }

    public FeedbackMsg(Long id) {
        this.id = id;
    }

    public FeedbackMsg(Long id, String descr, String date, String phoneModel) {
        this.id = id;
        this.descr = descr;
        this.date = date;
        this.phoneModel = phoneModel;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescr() {
        return descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getPhoneModel() {
        return phoneModel;
    }

    public void setPhoneModel(String phoneModel) {
        this.phoneModel = phoneModel;
    }

}
